### ISSUE TITLE
API Implementation works

### ISSUE THREAD

**Issue by LaysDragon** [Laysi/go-ecpay-sdk#4]
There is still some API Request and Return Data need to implement.
- Request
  - [x] AioCheckOut 
    > 5.產生訂單
  - [x] QueryTradeInfo
    > 8.查詢訂單
  - [ ] QueryTrade
    > 9.查詢信用卡單筆明細記錄
  - [ ] QueryPaymentInfo
    > 10.查詢 ATM/CVS/BARCODE 取號結果
  - [ ] CreditDetail
    > 11.信用卡請退款功能
  - [x] QueryCreditCardPeriodInfo
    > 13.信用卡定期定額訂單查詢
- Return Data
  - [x] OrderResult(ReturnURL/OrderResultURL)
    > 7.付款結果通知 - 應用場景Ⅰ
  - [ ] PeriodOrderResult (PeriodReturnURL)
    > 7.付款結果通知 - 應用場景Ⅱ
  - [ ] PaymentInfo (PaymentInfoURL)
    > 6.ATM、CVS 或 BARCODE 的取號結果通知
  - [ ] NeedExtraPaidInfo
    > 12.額外回傳的參數

## TODO
- [ ] 產生發票參數的API檢查

**Comment by LaysDragon** [comment]
- [x] QueryTradeInfo still need to do some test to figure what going #6

**Comment by LaysDragon** [comment]
- [x] ReturnData need to rename to OrderResult

**Comment by LaysDragon** [comment]
- [x] QueryPaymentInfo the openapi client cannot recognized the content-type from  ecapay server,since it is html/text insteadof application/json,I need to overwrite the template to fix the problem.
I plan to add a custom field to use as fall back while the content-type is wrong.
like `x-fallback-content`
> fix in #5
